<p><center><h3> Produtos </h3><a href="?edit=0">Adicionar Produto</center></a></p>

{if $edit >= 0}
	<form method="post" enctype="multipart/form-data"> 
		<label>
			Categoria: 
					<select name="data[categoria_id]">
						{section name=i loop=$categorias}
							<option value="{$categorias[i].id}" {if $edit neq 0}{if $produto.categoria_id eq $categorias[i].id}selected="selected"{/if}{/if}>
								{$categorias[i].nome}
							</option>
						{/section}								
					</select>
		</label>
		<label>
			Nome: <input type="text" name="data[nome]" {if $edit neq 0} value="{$produto.nome}" {/if}>	
		</label>
		<label>
			Autor: <input type="text" name="data[autor]" {if $edit neq 0} value="{$produto.autor}" {/if}>	
		</label>
		<label>
			Editora: <input type="text" name="data[editora]" {if $edit neq 0} value="{$produto.editora}" {/if}>	
		</label>
		<label>
			Valor: <input type="text" name="data[valor]" {if $edit neq 0} value="{$produto.valor}" {/if}>	
		</label>
		<label>
			Imagem: <input type="file" name="file">	
		</label>
		<label>
			Descrição: 
				<textarea rows="4" name="data[descricao]" disable>{if $edit neq 0}{$produto.descricao}{/if}</textarea>
		</label>
		<label>
			<input type="submit" name="salvar" value="Salvar">	
		</label>
		<input type="hidden" name="id" value="{$edit}">				
	</form>

	<div class="clearfix"></div>
{/if}


<table>
	<thead>
		<tr>
			<th>ID</th>
			<th>Nome</th>
			<th>Autor</th>
			<th>Editora</th>
			<th>Valor</th>
			<th>Ações</th>
		</tr>
	</thead>
	<tbody>
		{section name=i loop=$produtos}
			<tr>
				<td>{$produtos[i].id}</td>
				<td>{$produtos[i].nome}</td>
				<td>{$produtos[i].autor}</td>
				<td>{$produtos[i].editora}</td>
				<td>{$produtos[i].valor}</td>
				<td>
					<a href="?edit={$produtos[i].id}"><img src="images/icons/edit.png"></a> &nbsp;
					<a href="?delete={$produtos[i].id}"><img src="images/icons/delete.png"></a>				
				</td>
			</tr>
		{/section}
	</tbody>


</table>



